top.$App.composeTemplate = [ '<html><head></head><body style="margin:0; padding:0;"><style>div{line-height:28px;}</style>',
 '<table width="100%" border="0" cellpadding="0" cellspacing="0" background="/m2012/images/module/letter/doomsday/top_repeat_bg.jpg" style="width: 100%; background-color:#f3f3f3; background-repeat: repeat-x; background-position:left top;">',
   '<tbody>',
   '<tr>',
     '<td style="margin:0; padding:0;"><img src="/m2012/images/module/letter/doomsday/top_bg.jpg" style="text-align:left;"/></td>',
   '</tr>',
 '</tbody></table>',
 '<table width="100%" height="190" border="0" cellpadding="0" cellspacing="0" bgcolor="#f3f3f3" style="width: 100%;">',
   '<tbody><tr>',
     '<td valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">',
       '<tbody><tr>',
         '<td>&nbsp;</td>',
       '</tr>',
     '</tbody></table>',
     '<table width="95%" border="0" align="center" cellpadding="0" cellspacing="0" background="http://appmail3.mail.10086.cn/RmWeb/letterpaper/xinzhi_img/bg_dian.gif" >',
         '<tbody><tr>',
           '<td id="content139" valign="top" style="font-size:14px;line-height:28px;color: #000000"><div style="font-size: 13px; font-family: 宋体; color: #000000;">{content}</div><div style="clear: both;"><br></div><div style="clear: both;"><br></div><br><br><br><br><br><br><br><br><br></td>',
         '</tr>',
         '<tr>',
           '<td height="10" valign="top"></td>',
         '</tr>',
       '</tbody></table>',
       '<table width="100%" border="0" cellpadding="0" cellspacing="0">',
         '<tbody><tr>',
           '<td>&nbsp;</td>',
         '</tr>',
       '</tbody></table></td>',
   '</tr>',
 '</tbody></table>',
 '<table width="100%" border="0" cellpadding="0" cellspacing="0" background="/m2012/images/module/letter/doomsday/bt_repeat_bg.jpg" style="width: 100%; background-position: 0% 100%; background-repeat: repeat-x;">',
   '<tbody><tr>',
     '<td><img src="/m2012/images/module/letter/doomsday/bt_bg.jpg"  style="text-align:right; float:right;"/></td>',
   '</tr>',
 '</tbody></table>',
 '</body></html>'].join("");